#<% require 'kitchen-sync' %>
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3

platforms:
- name: amazon-2015.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-e7527ed7
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

suites:
  - name: default
    run_list:
      - recipe[pm2_application::default]
    attributes:

