---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[pm2_application::default]
    attributes:
